version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./static:/app/static
    ports:
      - $SERVER_PORT:$SERVER_PORT
    network_mode: host

  db:
    image: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    network_mode: host

  nginx:
    image: nginx
    environment:
      - NGINX_PORT=$NGINX_PORT
      - NGINX_APP_BASE_URL=http://$SERVER_HOST:$SERVER_PORT
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./static:/var/www/data/static
      - ./logs:/var/log/nginx
    ports:
      - $NGINX_PORT:$NGINX_PORT
    network_mode: host

volumes:
  postgres-volume:
